"""
This type stub file was generated by pyright.
"""

import inspect
from state_machine.models import Event, InvalidStateTransition, State
from state_machine.orm import get_adaptor

_temp_callback_cache = ...
def get_callback_cache(): # -> dict[Unknown, Unknown]:
    ...

def get_function_name(frame): # -> str:
    ...

def before(before_what): # -> (func: Unknown) -> Unknown:
    ...

def after(after_what): # -> (func: Unknown) -> Unknown:
    ...

def acts_as_state_machine(original_class): # -> Any:
    ...

