"""
This type stub file was generated by pyright.
"""

from __future__ import absolute_import
from state_machine.orm.base import BaseAdaptor
from state_machine.orm.mongoengine import get_mongo_adaptor
from state_machine.orm.sqlalchemy import get_sqlalchemy_adaptor

_adaptors = ...
def get_adaptor(original_class): # -> MongoAdaptor | SqlAlchemyAdaptor | NullAdaptor:
    ...

class NullAdaptor(BaseAdaptor):
    def extra_class_members(self, initial_state): # -> dict[str, Unknown]:
        ...
    
    def update(self, document, state_name): # -> None:
        ...
    


