"""
This type stub file was generated by pyright.
"""

class BaseAdaptor:
    def __init__(self, original_class) -> None:
        ...
    
    def get_potential_state_machine_attributes(self, clazz): # -> _GetMembersReturn:
        ...
    
    def process_states(self, original_class): # -> tuple[dict[Unknown, Unknown], State | None]:
        ...
    
    def process_events(self, original_class): # -> dict[Unknown, Unknown]:
        ...
    
    def modifed_class(self, original_class, callback_cache): # -> Any:
        ...
    
    def extra_class_members(self, initial_state):
        ...
    
    def update(self, document, state_name):
        ...
    


