"""
This type stub file was generated by pyright.
"""

from state_machine.orm.base import BaseAdaptor

class MongoAdaptor(BaseAdaptor):
    def get_potential_state_machine_attributes(self, clazz): # -> list[Unknown]:
        ...
    
    def extra_class_members(self, initial_state): # -> dict[str, Unknown]:
        ...
    
    def update(self, document, state_name): # -> None:
        ...
    


def get_mongo_adaptor(original_class): # -> MongoAdaptor | None:
    ...

