"""
This type stub file was generated by pyright.
"""

from state_machine.orm.base import BaseAdaptor

class SqlAlchemyAdaptor(BaseAdaptor):
    def extra_class_members(self, initial_state): # -> dict[str, Column]:
        ...
    
    def update(self, document, state_name): # -> None:
        ...
    
    def modifed_class(self, original_class, callback_cache):
        ...
    


def get_sqlalchemy_adaptor(original_class): # -> SqlAlchemyAdaptor | None:
    ...

